
version: "3.4"
services:
 vite_docker:
   image: node:alpine
   container_name: hr-frontend
   entrypoint: /bin/sh
   ports:
     - 84:84
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true
